using System;
using System.Collections.Generic;
using UnityEngine;

// Token: 0x020004A8 RID: 1192
public class YanSaveIdentifier : MonoBehaviour
{
	// Token: 0x06001E55 RID: 7765 RVA: 0x0017DECC File Offset: 0x0017C0CC
	public static GameObject GetObject(string id)
	{
		foreach (YanSaveIdentifier yanSaveIdentifier in YanSaveIdentifier.Identifiers)
		{
			if (yanSaveIdentifier.ObjectID == id)
			{
				return yanSaveIdentifier.gameObject;
			}
		}
		return null;
	}

	// Token: 0x06001E56 RID: 7766 RVA: 0x0017DF34 File Offset: 0x0017C134
	public static GameObject GetObject(SerializedGameObject serializedGameObject)
	{
		foreach (YanSaveIdentifier yanSaveIdentifier in YanSaveIdentifier.Identifiers)
		{
			if (yanSaveIdentifier.ObjectID == serializedGameObject.ObjectID)
			{
				return yanSaveIdentifier.gameObject;
			}
		}
		return null;
	}

	// Token: 0x06001E57 RID: 7767 RVA: 0x0017DFA0 File Offset: 0x0017C1A0
	public void OnEnable()
	{
		if (!YanSaveIdentifier.Identifiers.Contains(this))
		{
			YanSaveIdentifier.Identifiers.Add(this);
		}
		if (string.IsNullOrEmpty(this.ObjectID))
		{
			this.ObjectID = base.gameObject.name;
		}
	}

	// Token: 0x06001E58 RID: 7768 RVA: 0x0017DFD8 File Offset: 0x0017C1D8
	public void OnDestroy()
	{
		YanSaveIdentifier.Identifiers.Remove(this);
	}

	// Token: 0x04003C97 RID: 15511
	public string ObjectID;

	// Token: 0x04003C98 RID: 15512
	[HideInInspector]
	public bool AutoGenerated;

	// Token: 0x04003C99 RID: 15513
	[HideInInspector]
	public List<Component> EnabledComponents = new List<Component>();

	// Token: 0x04003C9A RID: 15514
	[HideInInspector]
	public List<DisabledYanSaveMember> DisabledProperties = new List<DisabledYanSaveMember>();

	// Token: 0x04003C9B RID: 15515
	[HideInInspector]
	public List<DisabledYanSaveMember> DisabledFields = new List<DisabledYanSaveMember>();

	// Token: 0x04003C9C RID: 15516
	[HideInInspector]
	public bool InitializedInspector;

	// Token: 0x04003C9D RID: 15517
	private static List<YanSaveIdentifier> Identifiers = new List<YanSaveIdentifier>();
}
